// Generated by gencpp from file cym_marker/Script.msg
// DO NOT EDIT!


#ifndef CYM_MARKER_MESSAGE_SCRIPT_H
#define CYM_MARKER_MESSAGE_SCRIPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cym_marker
{
template <class ContainerAllocator>
struct Script_
{
  typedef Script_<ContainerAllocator> Type;

  Script_()
    : uri()
    , name()  {
    }
  Script_(const ContainerAllocator& _alloc)
    : uri(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _uri_type;
  _uri_type uri;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::cym_marker::Script_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cym_marker::Script_<ContainerAllocator> const> ConstPtr;

}; // struct Script_

typedef ::cym_marker::Script_<std::allocator<void> > Script;

typedef boost::shared_ptr< ::cym_marker::Script > ScriptPtr;
typedef boost::shared_ptr< ::cym_marker::Script const> ScriptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cym_marker::Script_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cym_marker::Script_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cym_marker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'HasHeader': False, 'IsFixedSize': False, 'IsMessage': True}
// {'cym_marker': ['/home/yifengn2/catkin_ws3/src/Cymulator/cym_marker/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'rosgraph_msgs': ['/opt/ros/kinetic/share/rosgraph_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct HasHeader< ::cym_marker::Script_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cym_marker::Script_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cym_marker::Script_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cym_marker::Script_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cym_marker::Script_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cym_marker::Script_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cym_marker::Script_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f69c1b3fe777d3b60253f82738d336d0";
  }

  static const char* value(const ::cym_marker::Script_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf69c1b3fe777d3b6ULL;
  static const uint64_t static_value2 = 0x0253f82738d336d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cym_marker::Script_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cym_marker/Script";
  }

  static const char* value(const ::cym_marker::Script_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cym_marker::Script_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] uri\n\
string name\n\
\n\
";
  }

  static const char* value(const ::cym_marker::Script_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cym_marker::Script_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uri);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Script_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cym_marker::Script_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cym_marker::Script_<ContainerAllocator>& v)
  {
    s << indent << "uri[]" << std::endl;
    for (size_t i = 0; i < v.uri.size(); ++i)
    {
      s << indent << "  uri[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.uri[i]);
    }
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYM_MARKER_MESSAGE_SCRIPT_H
