(cl:in-package cym_marker-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACTION-VAL
          ACTION
          NS-VAL
          NS
          ID-VAL
          ID
          LAYER-VAL
          LAYER
          TYPE-VAL
          TYPE
          LIFETIME-VAL
          LIFETIME
          POSE-VAL
          POSE
          SCALE-VAL
          SCALE
          MATERIAL-VAL
          MATERIAL
          POINT-VAL
          POINT
          TEXT-VAL
          TEXT
          PARENT-VAL
          PARENT
          VISIBILITY-VAL
          VISIBILITY
))